spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shiro-learn?characterEncoding=utf-8&useSSL=true"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
  swagger:
    title: "shiro learn rest api."
    version: "1.0"
server:
  port: 9090

mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/**/*Mapper.xml
  config-location: classpath:/config/mybatis-config.xml

#配置logback配置文件位置
logging:
  config: classpath:spring-logback.xml
  level:
    com:
      wx:
        tourism: debug